default: &default
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] || Rails.application.credentials.auth0_domain %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] || Rails.application.credentials.auth0_client_id %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] || Rails.application.credentials.auth0_client_secret %>

development:
  <<: *default

test: 
  auth0_domain: "example.com"
  auth0_client_id: "client_id"
  auth0_client_secret: "client_secret"

production: 
  <<: *default
